### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by a2jinhee** [OpenDriveLab/PersFormer_3DLane#118]
Hello! I am trying to evaluate Openlane validation datasets, and have successfully went through loading the datatsets and finished all installation process including setup.py. Also, checkpoint file is loaded without fail. 

However, whenever the checkpoint file starts to load, 'module' object is not callable is triggered in: 

```
Convert model with Sync BatchNorm
=> loading checkpoint '/home/heven/model_ws/src/PersFormer_3DLane-main/data_splits/openlane/PersFormer/model_best1.pth.tar'
0it [00:01, ?it/s]
Traceback (most recent call last):
  File "main_persformer.py", line 44, in <module>
    main()
  File "main_persformer.py", line 40, in main
    runner.eval()
  File "/home/heven/model_ws/src/PersFormer_3DLane-main/experiments/runner.py", line 667, in eval
    loss_list, eval_stats = self.validate(model, None, vis=True)
  File "/home/heven/model_ws/src/PersFormer_3DLane-main/experiments/runner.py", line 457, in validate
    output_net = nms_bev(output_net, args)
  File "/home/heven/model_ws/src/PersFormer_3DLane-main/utils/utils.py", line 1042, in nms_bev
    keep, num_to_keep, _ = nms(output_net_nms, scores, overlap=args.nms_thres_3d, top_k=args.max_lanes)
```
I attach my terminal and file hierarchy. 

![image](https://github.com/OpenDriveLab/PersFormer_3DLane/assets/76829731/6b391ca0-6906-4754-8e49-d03b414dab9f)
![image](https://github.com/OpenDriveLab/PersFormer_3DLane/assets/76829731/8f817d70-9f86-41b5-a94c-a968ad310bf9)

**Comment by ilnehc** [comment]
@a2jinhee It seems that the nms package is not successfully compiled for calling. Could you double-check its setup process, especially the corresponding cuda issues mentioned in the installation doc?

**Comment by a2jinhee** [comment]
@ilnehc Our version - Cuda : 11.6, torch : 13.1

Yes, as shown in the INSTALL.md  : 

## Known Issues
- If you couldn't compile the `nms` operator because of error like `nvcc fatal   : Unsupported gpu architecture 'compute_86'`, try specifying your cuda path to some environment variable. Following is an example for cuda-11.4
    ```
    export LIBRARY_PATH=/usr/local/cuda-11.4/lib64/:$LIBRARY_PATH
    export LD_LIBRARY_PATH=/usr/local/cuda-11.4/lib64/:$LD_LIBRARY_PATH
    export PATH=/usr/local/cuda-11.4/bin/:$PATH
    export CUDA_HOME=/usr/local/cuda-11.4/
    ```
We did this in our terminal! 

In short, 
1) We tried with CUDA 11.6 but it did not work and showed module not callable error
2) We tried the method in INSTALLATION.md but showed same error. 
3)We also switched to CUDA 11.4 and CUDA 11.1 with pytorch version 1.13.1 and did it again, but it did not work. 

Can you elaborate on the INSTALLATION.md method a little bit more? Or is there a way to go around this problem?
