### ISSUE TITLE
UnboundLocalError: local variable '_label_cam_height' referenced before assignment

### ISSUE THREAD

**Issue by zy6588** [OpenDriveLab/PersFormer_3DLane#122]
Original Traceback (most recent call last):
  File "/home/zhangy/anaconda3/envs/3dl/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhangy/anaconda3/envs/3dl/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhangy/anaconda3/envs/3dl/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhangy/github/PersFormer_3DLane-main/data/Load_Data.py", line 906, in __getitem__
    return self.WIP__getitem__(idx)
  File "/home/zhangy/github/PersFormer_3DLane-main/data/Load_Data.py", line 742, in WIP__getitem__
    gt_cam_height = _label_cam_height
UnboundLocalError: local variable '_label_cam_height' referenced before assignment

**Comment by zy6588** [comment]
在使用apollo数据集的时候要修改./config/persformer_apollo.py。并且在main_persformer.py默认是persformer_openlane.config(args)
