### ISSUE TITLE
error when importing MultiScaleDeformableAttention

### ISSUE THREAD

**Issue by MoHassoubah** [OpenDriveLab/PersFormer_3DLane#95]
Hello,

I try to run the training but I'm getting this import error
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention

I'm using windows machine with cuda version 11.3.1, yet I cant setup it or install it using pip from here
https://pypi.org/project/MultiScaleDeformableAttention/

**Comment by RicardLee** [comment]
Hi，we can't reproduce this problem. For more information, please share more logs.

**Comment by MoHassoubah** [comment]
Thank you 
these are the logs I get

NOTE: Redirects are currently not supported in Windows or MacOs.
G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please   
change it to read from `os.environ['LOCAL_RANK']` instead. See     
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [CAI1-W20204.vnet.valeo.com]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [CAI1-W20204.vnet.valeo.com]:29500 (system error: 10049 - The requested address is not valid in its context.).
Traceback (most recent call last):
  File "G:\Hassoubah\persformer\main_persformer.py", line 21, in <module>
    from experiments.runner import *
  File "G:\Hassoubah\persformer\experiments\runner.py", line 31, in <module>
    from models.PersFormer import PersFormer
  File "G:\Hassoubah\persformer\models\PersFormer.py", line 26, in 
<module>
    from models.networks.Layers import EncoderLayer
  File "G:\Hassoubah\persformer\models\networks\Layers.py", line 22, in <module>
    from models.ops.modules import MSDeformAttn, IdentityMSDeformAttn, DropoutMSDeformAttn
  File "G:\Hassoubah\persformer\models\ops\modules\__init__.py", line 9, in <module>
    from .ms_deform_attn import MSDeformAttn, IdentityMSDeformAttn, DropoutMSDeformAttn
  File "G:\Hassoubah\persformer\models\ops\modules\ms_deform_attn.py", line 21, in <module>
    from ..functions import MSDeformAttnFunction
  File "G:\Hassoubah\persformer\models\ops\functions\__init__.py", 
**line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "G:\Hassoubah\persformer\models\ops\functions\ms_deform_attn_func.py", line 18, in <module>
    import MultiScaleDeformableAttention as MSDA
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'**
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26740) of binary: G:\Hassoubah\envs\pytorch-env\python.exe
Traceback (most recent call last):
  File "G:\Hassoubah\envs\pytorch-env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "G:\Hassoubah\envs\pytorch-env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\launch.py", line 193, in <module>
    main()
  File "G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\launch.py", line 189, in main
    launch(args)
  File "G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\launch.py", line 174, in launch
    run(args)
  File "G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\run.py", line 752, in run
    elastic_launch(
  File "G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))  File "G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\launcher\api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================       
main_persformer.py FAILED
------------------------------------------------------------       
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------       
Root Cause (first observed failure):
[0]:
  time      : 2023-01-05_19:20:07
  host      : CAI1-W20204.vnet.valeo.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26740)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by MoHassoubah** [comment]
Thank you 
these are the logs I get

NOTE: Redirects are currently not supported in Windows or MacOs.
G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please   
change it to read from `os.environ['LOCAL_RANK']` instead. See     
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [CAI1-W20204.vnet.valeo.com]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [CAI1-W20204.vnet.valeo.com]:29500 (system error: 10049 - The requested address is not valid in its context.).
Traceback (most recent call last):
  File "G:\Hassoubah\persformer\main_persformer.py", line 21, in <module>
    from experiments.runner import *
  File "G:\Hassoubah\persformer\experiments\runner.py", line 31, in <module>
    from models.PersFormer import PersFormer
  File "G:\Hassoubah\persformer\models\PersFormer.py", line 26, in 
<module>
    from models.networks.Layers import EncoderLayer
  File "G:\Hassoubah\persformer\models\networks\Layers.py", line 22, in <module>
    from models.ops.modules import MSDeformAttn, IdentityMSDeformAttn, DropoutMSDeformAttn
  File "G:\Hassoubah\persformer\models\ops\modules\__init__.py", line 9, in <module>
    from .ms_deform_attn import MSDeformAttn, IdentityMSDeformAttn, DropoutMSDeformAttn
  File "G:\Hassoubah\persformer\models\ops\modules\ms_deform_attn.py", line 21, in <module>
    from ..functions import MSDeformAttnFunction
  File "G:\Hassoubah\persformer\models\ops\functions\__init__.py", 
line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "G:\Hassoubah\persformer\models\ops\functions\ms_deform_attn_func.py", line 18, in <module>
    import MultiScaleDeformableAttention as MSDA
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26740) of binary: G:\Hassoubah\envs\pytorch-env\python.exe
Traceback (most recent call last):
  File "G:\Hassoubah\envs\pytorch-env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "G:\Hassoubah\envs\pytorch-env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\launch.py", line 193, in <module>
    main()
  File "G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\launch.py", line 189, in main
    launch(args)
  File "G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\launch.py", line 174, in launch
    run(args)
  File "G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\run.py", line 752, in run
    elastic_launch(
  File "G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))  File "G:\Hassoubah\envs\pytorch-env\lib\site-packages\torch\distributed\launcher\api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================       
main_persformer.py FAILED
------------------------------------------------------------       
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------       
Root Cause (first observed failure):
[0]:
  time      : 2023-01-05_19:20:07
  host      : CAI1-W20204.vnet.valeo.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26740)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by huangmozhi9527** [comment]
Hi, please share logs when you setup or install 'MultiScaleDeformableAttention'.
